### ISSUE TITLE
Implement Merge sort in any language

### ISSUE THREAD

**Issue by Aju100** [Hacktoberfest-Nepal/Algorithms#1]
Hey there, implement merge sort in any language with the folder of a particular language.

**Comment by rgrupesh** [comment]
I would like to work on this issue using Python. Please, assign me.

**Comment by Aju100** [comment]
@rgrupesh  sure. you can

**Comment by Aju100** [comment]
@rgrupesh  before, working on this issue, please register and make ur first PR in our https://github.com/Hacktoberfest-Nepal/Your-First-PR Repo
