### ISSUE TITLE
Implement algorithms

### ISSUE THREAD

**Issue by Aju100** [Hacktoberfest-Nepal/Algorithms#9]
Hello coders,

Let's open a PR by creating any algorithms.

**Comment by Ajay0511** [comment]
Can we write any Algorithms related to any topics like Data Structures?

**Comment by Aju100** [comment]
@Ajay0511  yeah sure.

**Comment by akshay399** [comment]
hey, can i add algorithms for different asterisk patterns using python?

**Comment by Aju100** [comment]
@akshay399  sure

**Comment by akanksha0820** [comment]
I have contributed to this repository #32. Kindly review the pull request and pls add  Hacktoberfest- accepted label if you merge it.
